config/routes.rb
NeedOTron::Application.routes.draw do
  resources :needs do
    collection do
      resource :imports, :only => [:new, :create]
    end
    resources :sources
    resources :fact_checkers do
      collection do
        get :search
      end
    end
    resources :accountabilities do
      collection do
        get :search
      end
    end
    member do
      get 'print'
    end
  end

  match 'search(/*filters)' => 'search#index', as: 'filtered_search'
  match 'search' => 'search#index', as: 'search'
  root :to => "search#index"
end

app/models/source.rb
class Source < ActiveRecord::Base
  belongs_to :need

  KINDS = [
    'legacy_service',
    'existing_service',
    'government_campaign',
    'government_obligation',
    'legal_framework',
    'official_channel',
    'search_behaviour',
    'user_request'
  ]

  validates :kind, :presence => true, :inclusion => { :in => KINDS }
end

app/controllers/sources_controller.rb
class SourcesController < InheritedResources::Base
  belongs_to :need
  actions :all, :except => [:show, :index]
end

app/views/sources/_form.html.erb
<%= semantic_form_for([@need, @source]) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @source.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.inputs do %>
    <%= f.input :title, :as => :string, :input_html => { :class => "input-block-level" } %>
    <%= f.input :kind, :as => :select, :collection => Source::KINDS.map {|k| [k.humanize, k]} %>
    <%= f.input :url, :label => "URL", :as => :string, :input_html => { :class => "input-block-level" } %>
    <%= f.input :body, :label => "Notes", :as => :text, :rows => "4", :input_html => { :class => "input-block-level" } %>
  <% end %>
  <%= f.actions %>

<% end %>
<% if @source.persisted? %>
  <%= link_to "Delete this source", need_source_path(@need, @source), :method => :delete, :confirm => "Are you sure?" %>
<% end %>

app/views/sources/edit.html.erb
<section class="span12 centred">
  <h1>Edit source</h1>

  <%= render 'form' %>
</section>

<% content_for :current_state, @need.status %>

app/views/sources/new.html.erb
<section class="span12 centred">
  <h1>Add source</h1>

  <%= render 'form' %>
</section>

<% content_for :current_state, @need.status %>