config/routes.rb
NeedOTron::Application.routes.draw do
  resources :needs do
    collection do
      resource :imports, :only => [:new, :create]
    end
    resources :sources
    resources :fact_checkers do
      collection do
        get :search
      end
    end
    resources :accountabilities do
      collection do
        get :search
      end
    end
    member do
      get 'print'
    end
  end

  match 'search(/*filters)' => 'search#index', as: 'filtered_search'
  match 'search' => 'search#index', as: 'search'
  root :to => "search#index"
end

app/models/need.rb
class Need < ActiveRecord::Base
  class_attribute :index_command

  class CannotDeleteStartedNeed < Exception; end

  MAXIMUM_POLICY_DEPARTMENTS = 5
  MAXIMUM_FACT_CHECKERS = 5

  FORMAT_ASSIGNED  = "format-assigned"
  READY_FOR_REVIEW = "ready-for-review"
  IN_PROGRESS      = "in-progress"
  ICEBOX           = "icebox"
  NEW              = "new"
  DONE             = "done"

  STATUSES              = [NEW, READY_FOR_REVIEW, FORMAT_ASSIGNED, IN_PROGRESS, DONE, ICEBOX]
  PRIORITIES_FOR_SELECT = [['low', 1], ['medium', 2], ['high', 3]]
  PRIORITIES            = {1 => 'low', 2 => 'medium', 3 => 'high'}

  belongs_to :kind
  belongs_to :decision_maker, :class_name => 'User'
  belongs_to :formatting_decision_maker, :class_name => 'User'
  belongs_to :creator, :class_name => 'User'

  has_many :justifications
  has_many :existing_services
  has_many :directgov_links
  has_many :fact_checkers
  has_many :sources

  belongs_to :writing_department

  has_many :accountabilities
  has_many :policy_departments, :through => :accountabilities, :source => :department

  accepts_nested_attributes_for :accountabilities, :reject_if => :all_blank
  accepts_nested_attributes_for :fact_checkers, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :directgov_links, :allow_destroy => true, :reject_if => proc { |atts| atts['directgov_id'].blank? }
  accepts_nested_attributes_for :existing_services, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :justifications, :allow_destroy => true, :reject_if => :all_blank

  scope :undecided, where(:decision_made_at => nil)
  scope :decided, where('decision_made_at IS NOT NULL')
  scope :in_state, proc { |s| where(:status => s).includes([:fact_checkers, :accountabilities, :creator, :kind, :sources, :writing_department]) }
  default_scope order('priority, title')

  before_save :record_decision_info, :if => :reason_for_decision_changed?
  before_save :record_formatting_decision_info, :if => :reason_for_formatting_decision_changed?
  before_save :set_creator, :on => :create
  before_validation :delete_empty_fact_checkers, :delete_empty_accountabilities

  before_destroy :check_need_is_not_started

  validate :status, :in => STATUSES
  validates_presence_of :priority, :if => proc { |a| a.status == FORMAT_ASSIGNED }
  validates_presence_of :url, :if => proc { |a| a.status == 'done' }

  def set_creator
    self.creator = Thread.current[:current_user]
  end

  include Tire::Model::Search
  include Tire::Model::Callbacks

  index_name("blah-#{Rails.env}-needs")
  mapping do
    indexes :id,          type: 'integer',     index: :not_analyzed
    indexes :title,       type: 'multi_field', fields: {
      :title            => { :type => "string",      :analyzer => "snowball" },
      :"title.exact"    => { :type => "string",      :index => :not_analyzed }
    }

    indexes :description, analyzer: 'snowball', boost: 20
    indexes :notes
    indexes :reason_for_decision
    indexes :reason_for_formatting_decision
    indexes :status
    indexes :priority, :index => :not_analyzed
    indexes :kind, :index => :not_analyzed
    indexes :writing_department
    indexes :created_at
    indexes :updated_at
    indexes :decision_made_at
    indexes :formatting_decision_made_at
    indexes :tags
    indexes :updated_at, :index => :not_analyzed
  end

  def to_indexed_json
    standard_fields = %w(id title description notes reason_for_decision reason_for_formatting_decision status priority)
    associations = %w(kind writing_department)
    date_fields = %w{created_at updated_at decision_made_at formatting_decision_made_at}

    details = {}
    standard_fields.each do |label|
      value = send(label.to_sym)
      details[label] = value if value.present?
    end

    associations.each do |label|
      details[label] = send(label.to_sym).name if send(label.to_sym)
    end

    details['tags'] = tag_list.to_s.split(/ *, */)

    date_fields.each do |date_field|
      value = send(date_field.to_sym)
      details[date_field] = value.to_s if value.present?
    end
    details.to_json
  end

  def record_decision_info
    if self.decision_made_at.nil? and self.reason_for_decision.present?
      self.decision_made_at = Time.zone.now
      self.decision_maker = Thread.current[:current_user]
    end
  end

  def record_formatting_decision_info
    if self.formatting_decision_made_at.nil? and self.reason_for_formatting_decision.present?
      self.formatting_decision_made_at = Time.zone.now
      self.formatting_decision_maker = Thread.current[:current_user]
    end
  end

  def delete_empty_accountabilities
    accountabilities.each do |ac|
      ac.mark_for_destruction if ac.department_id.blank?
    end
  end

  def delete_empty_fact_checkers
    fact_checkers.each do |fc|
      fc.mark_for_destruction if fc.email.blank?
    end
  end

  def format_assigned?
    [FORMAT_ASSIGNED, IN_PROGRESS, DONE, ICEBOX].include?(status)
  end

  def being_worked_on?
    [FORMAT_ASSIGNED, IN_PROGRESS, DONE].include?(status)
  end

  def in_progress?
    [IN_PROGRESS, DONE].include?(status)
  end

  STATUSES.each do |status_label|
    define_method "#{status_label}?" do
      status == status_label
    end
  end

  def decision_made?
    decision_made_at.present?
  end

  def formatting_decision_made?
    formatting_decision_made_at.present?
  end

  def prioritised?
    !priority.nil?
  end

  def named_priority
    PRIORITIES[priority]
  end

  def priority=(name_or_value)
    if PRIORITIES.keys.include?(name_or_value)
      write_attribute(:priority, name_or_value)
      return name_or_value
    end
    PRIORITIES_FOR_SELECT.each do |name, value|
      if value.to_s == name_or_value
        write_attribute(:priority, value)
        return value
      end
      if name_or_value[0] == name[0]
        write_attribute(:priority, value)
        return named_priority
      end
    end
    nil
  end

  def current_fact_checker_emails
    fact_checkers.collect { |f| f.email }
  end

  def add_fact_checker_with_email(email)
    fact_checkers.build(contact: Contact.find_or_initialize_by_email(email))
  end

  def remove_fact_checker_with_email(email)
    fact_checkers.select { |fc| fc.contact.email == email }.each do |fc|
      fact_checkers.destroy(fc)
    end
  end

  def current_accountability_names
    accountabilities.collect { |a| a.department.name }
  end

  def add_accountability_with_name(name)
    accountabilities.build(department: Department.find_or_initialize_by_name(name))
  end

  def remove_accountability_with_name(name)
    accountabilities.select { |a| a.department.name == name }.each do |a|
      accountabilities.destroy(a)
    end
  end

  def check_need_is_not_started
    raise(CannotDeleteStartedNeed.new) if in_progress?
  end

end

app/controllers/needs_controller.rb
require 'needs_csv'
require 'csv'

class NeedsController < InheritedResources::Base

  before_filter :ensure_user_is_admin!, :only => [:new, :edit, :create, :destroy]

  has_scope :in_state
  skip_before_filter [:authenticate_user!, :require_signin_permission!], :if => lambda { |c|
    c.action_name == 'show' && c.request.format.json?
  }

  rescue_from Need::CannotDeleteStartedNeed do
    flash[:alert] = "A need which has been started can't be destroyed"
    redirect_to @need
  end

  def index
    index! do |format|
      format.csv { render :csv => NeedsCsv.new(collection, Time.zone.now) }
    end
  end

  def show
    show! do |format|
      format.json
    end
  end

  def print
    @need = Need.find params[:id]
    render :layout => false
  end

  def update
    update! do |success, failure|
      failure.html {
        if request.referer.match(/needs\/\d+$/)
          @need.reload
          flash.now[:alert] = "We weren't able to save your changes. Please review the form below and try again"
          render :action => 'show'
        else
          render :action => 'edit'
        end
      }
    end
  end

  def collection
    @needs ||= Need.includes(:fact_checkers, :sources, :kind, :writing_department, {accountabilities: :department})
  end
end

app/helpers/needs_helper.rb
module NeedsHelper
  def start_work_link(need)
    start_work = "#{Plek.current.find("panopticon")}/artefacts/new"

    if need.status == 'in-progress' || need.status == 'done'
      title = 'Continue work on this need'
    else
      title = 'Start work on this need'
    end

    form_tag start_work, :method => 'get', :target => '_blank' do
      [
        hidden_field_tag("artefact[name]", "CHANGE ME: #{need.title}").html_safe,
        hidden_field_tag("artefact[owning_app]", "publisher").html_safe,
        hidden_field_tag("artefact[need_id]", need.id).html_safe,
        hidden_field_tag("artefact[kind]", need.kind.to_s.downcase).html_safe,
        hidden_field_tag("artefact[tags]", need.tag_list).html_safe,
        hidden_field_tag("artefact[department]", need.writing_department).html_safe
      ].join.html_safe + \
      button_tag(title, :type => "submit", :disable_with => 'Working...', :class => 'btn btn-block btn-large btn-primary').html_safe
    end.html_safe
  end

  def assign_work_link(need)
    start_work =  "#{Plek.current.find("panopticon")}/artefacts"
    start_work += "?return_to=#{CGI.escape(request.url)}"

    form_tag start_work, :method => 'post', :target => '_blank' do
      [
        hidden_field_tag("artefact[name]", "CHANGE ME: #{need.title}").html_safe,
        hidden_field_tag("artefact[slug]", "change-me-for-need-#{need.id}").html_safe,
        hidden_field_tag("artefact[owning_app]", "publisher").html_safe,
        hidden_field_tag("artefact[need_id]", need.id).html_safe,
        hidden_field_tag("artefact[kind]", need.kind.to_s.downcase).html_safe,
        hidden_field_tag("artefact[tags]", need.tag_list).html_safe
      ].join.html_safe + \
      submit_tag('Assign need', :disable_with => 'Working...', :class => 'btn btn-block btn-large').html_safe
    end.html_safe
  end

  def search_link_with_added_filter(params, filters, additional_filters)
    new_params = deep_copy(params.to_hash)
    new_params.delete('page')
    new_filters = deep_copy(filters.to_hash)
    additional_filters.each do |field, value|
      new_filters[field] ||= []
      new_filters[field] << value
    end
    new_params["filters"] = filter_to_path(new_filters)
    filtered_search_path(new_params)
  end

  def search_link_with_removed_filter(params, filters, filters_to_remove)
    new_params = deep_copy(params.to_hash)
    new_params.delete('page')
    new_filters = deep_copy(filters.to_hash)
    filters_to_remove.each do |field, value|
      next unless new_filters.has_key?(field)
      new_filters[field].delete(value)
    end
    new_params["filters"] = filter_to_path(new_filters)
    new_params.delete("filters") unless new_params["filters"]
    filtered_search_path(new_params)
  end

  def search_link_for_page(params, filters = nil, page = nil)
    new_params = deep_copy(params.to_hash)
    if filters
      new_params["filters"] = filter_to_path(filters)
    end
    new_params.delete('page')
    new_params['page'] = page if page
    filtered_search_path(new_params)
  end

  def named_priority priority
    Need::PRIORITIES[priority.to_i]
  end

  def filter_to_path(filters_hash)
    path = []
    filters_hash.each do |field, values|
      [*values].each do |value|
        path.concat([field, parameterize_filter(value)])
      end
    end
    path
  end

  def parameterize_filter(param)
    param.to_s.gsub("/","|")
  end

  def self.deparameterize_filter(param)
    param.gsub("|","/")
  end

  def filtering_by?(field, value)
    @filters[field] && @filters[field].include?(value)
  end

  def pagination_link(page_number, label, classes = [])
    classes = classes.is_a?(String) ? classes.split(' ') : classes.clone
    classes << 'disabled' unless @search.pages.include?(page_number)
    classes << 'active' if @current_page == page_number
    if (classes & %w{disabled active}).present?
      content_tag(:li, class: classes) do
        content_tag(:span, label)
      end
    else
      content_tag(:li, class: classes) do
        link_to label, search_link_for_page(params, @filters, page_number)
      end
    end
  end

  def sortable_heading(field)
    css_classes = []
    new_sort_dir = 'asc'
    if params[:sort_by] == field
      raise "Bad sort dir" unless %w{asc desc}.include?(params[:sort_dir])
      css_classes << "sorting-#{params[:sort_dir]}"
      new_sort_dir = params[:sort_dir] == 'asc' ? 'desc' : 'asc'
    end
    content_tag(:th, :class => css_classes, :scope => 'col') do
      link_to(t("field.short.#{field}"), search_link_for_page(params.merge(sort_by: field, sort_dir: new_sort_dir)))
    end
  end

  def deep_copy(object)
    Marshal.restore(Marshal.dump(object))
  end

  def accountabilities_for(need)
    (0...Need::MAXIMUM_POLICY_DEPARTMENTS).map { |i| need.accountabilities.all[i] || need.accountabilities.build }
  end

  def label_for(status)
    case status
    when 'new' then 'label-inverse'
    when 'done' then 'label-success'
    when %w{bin icebox} then ''
    when 'in-progress' then 'label-warning'
    when 'format-assigned' then 'label-info'
    when 'ready-for-review' then 'label-review'
    end
  end

end

app/views/needs/_decision.html.erb
<div class="format-assigned well">
  <h3>Ready to make a decision?</h3>
  <%= semantic_form_for(@need) do |f| %>
    <%= f.inputs do %>
      <%= f.input :kind %>
      <%= f.input :status, :input_html => {:value => 'format-assigned'}, :as => 'hidden', :label => false %>
      <%= f.input :priority, :as => :select, :collection => Need::PRIORITIES_FOR_SELECT %>
      <%= f.input :reason_for_formatting_decision, :input_html => { :class => "input-block-level" } %>
    <% end %>
    <%= f.actions do %>
      <%= f.action :submit, label: 'Decision made' %>
    <% end %>
  <% end %>
</div>

app/views/needs/_directgov_link_fields.html.erb
<li class="nested_item">
  <fieldset class="inputs">
    <ol>
    <%= f.input :directgov_id, :as => :string, :required => true, :label => "Directgov ID" %>
    <%= f.input :title, :as => :string, :input_html => { :disabled => true } %>
    <li class="delete-item"><%= link_to_remove_fields "Delete", f %></li>
    </ol>
  </fieldset>
</li>

app/views/needs/_errors.html.erb
<div id="error_explanation">
  <h2><%= pluralize(@need.errors.count, "error") %> prohibited this need from being saved:</h2>

  <ul>
  <% @need.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>

app/views/needs/_existing_service_fields.html.erb
<li class="nested_item">
  <fieldset class="inputs">
    <ol>
      <%= f.input :description, :input_html => { :rows => "4" } %>
      <%= f.input :link, :as => :string %>
      <%= f.input :government_run %>
      <%= f.input :kind, :collection => %W(online offline), :as => :radio %>
      <li class="delete-item"><%= link_to_remove_fields "Delete", f %></li>
    </ol>
  </fieldset>
</li>

app/views/needs/_form.html.erb
<%= semantic_bootstrap_nested_form_for(@need) do |f| %>
  <% if @need.errors.any? %>
    <%= render 'errors' %>
  <% end %>

  <%= f.inputs :id => 'overview' do %>
    <%= f.input :title, :label => 'Need *', :input_html => { :class => "input-block-level" } %>
    <%= f.input :description, :label => 'Context', :hint => "provide some information about the circumstances surrounding this need", :input_html => { :class => "input-block-level" } %>
    <%= f.input :tag_list, :as => :string, :label => 'Tags', :hint => "separate tags with commas", :input_html => { :class => "input-block-level" } %>
  <% end %>

  <% if f.object.persisted? %>
    <%= f.inputs :id => 'metadata', :name => 'Product decision' do %>
      <%= f.input :kind %>
      <%= f.input :status, :collection => Need::STATUSES %>
      <%= f.input :url, :input_html => { :class => "input-block-level" } %>
      <%= f.input :priority, :as => 'select', :collection => Need::PRIORITIES_FOR_SELECT if @need.format_assigned?%>
      <% if @need.format_assigned? %>
        <%= f.input :reason_for_formatting_decision, :input_html => { :class => "input-block-level" } %>
      <% end %>
      <%= f.input :writing_department, :label => 'Writing team' %>

      <%= f.inputs "Policy owners" do %>
        <ul class="nested_fields">
          <%= f.semantic_fields_for :accountabilities do |accountability| %>
            <li>
              <%= accountability.input :department, :as => :select, :collection => Department.order('name'), :label => false %>
              <%= accountability.link_to_remove "Remove" %>
            </li>
          <% end %>
          <%= f.link_to_add "Add a policy owner", :accountabilities %>
        </ul>
      <% end %>

      <%= f.inputs "Fact checkers" do %>
        <ul class="nested_fields">
          <%= f.semantic_fields_for :fact_checkers do |fact_checker| %>
            <li>
              <%= fact_checker.input :email, :required => false, :label => false %>
              <%= fact_checker.link_to_remove "Remove" %>
            </li>
          <% end %>
          <%= f.link_to_add "Add a fact checker", :fact_checkers %>
        </ul>
      <% end %>

    <% end %>
  <% end %>

  <%= f.actions %>

  <p style="text-align: right"><%= link_to raw('or return to list of needs without making changes &rarr;'), needs_path(:in_state => @need.status) %></p>
<% end %>

app/views/needs/_icebox.html.erb
<div class="icebox well">
  <h3>Want to icebox this?</h3>
  <%= semantic_form_for(@need) do |f| %>
    <%= f.inputs do %>
      <%= f.input :status, :input_html => {:value => 'icebox'}, :label => false, :as => 'hidden' %>
      <%= f.input :reason_for_decision, :input_html => { :class => "input-block-level" } %>
    <% end %>
    <%= f.actions do %>
      <%= f.action :submit, label: 'Icebox it' %>
    <% end %>
  <% end %>
</div>

app/views/needs/_justification_fields.html.erb
<li class="nested_item">
  <fieldset class="inputs">
    <ol>
    <%= f.input :evidence_type %>
    <%= f.input :details, :input_html => { :rows => "4" } %>

    <%= f.input :file, as: :file, input_html: {disabled: true}, hint: 'File upload is currently disabled' %>

    <li class="delete-item"><%= link_to_remove_fields "Delete", f %></li>
    </ol>
  </fieldset>
</li>

app/views/needs/_mark_done.html.erb
<div class="done well">
  <h3>Is the implementation complete?</h3>
  <%= semantic_form_for(@need) do |f| %>
    <%= f.inputs do %>
      <%= f.input :status, :input_html => {:value => 'done'}, :as => 'hidden', :label => false %>
      <%= f.input :url,  :input_html => { :class => "input-block-level" } %>
    <% end %>
    <%= f.actions do %>
      <%= f.action :submit, label: 'It is done' %>
    <% end %>
  <% end %>
</div>

app/views/needs/_needs_display.html.erb
<table id="needs-table" class="table table-striped">
  <thead>
    <tr>
      <% if local_assigns[:sortable_columns] %>
        <%= sortable_heading('id') %>
        <%= sortable_heading('title') %>
        <%= sortable_heading('kind') %>
        <%= sortable_heading('priority') %>
        <%= sortable_heading('updated_at') %>
      <% else %>
        <th scope="col">ID</th>
        <th scope="col">Title</th>
        <th scope="col">Format</th>
        <th scope="col">Priority</th>
        <th scope="col">Last updated</th>
      <% end %>

      <% if current_user.is_admin? %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% needs.each do |need| %>
      <tr>
        <td>#<%= need.id %></td>
        <th scope="row" style="width: 50%"><%= link_to need.title, need %> <% if !params[:in_state] %><span class="label <%= label_for need.status %>"><%= status_name need.status %></small><% end %></th>
        <td class="need"><%= need.kind || "-" %></td>
        <td><%= named_priority need.priority %></td>
        <td><%= time_ago_in_words(need.updated_at, true) %></td>
        <% if current_user.is_admin? %>
          <td><%= link_to 'Edit', edit_need_path(need) %></td>
          <td><%= link_to 'Delete', need, confirm: 'Are you sure?', method: :delete %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<p id="csv-download"><a class="button" href="<%= needs_path(:format => 'csv', :in_state => params[:in_state]) %>">Download as a CSV</a></p>
<% if current_user.is_admin? %>
  <p id="csv-upload"><%= link_to("Import a CSV with updated data", new_imports_path) %></p>
<% end %>

app/views/needs/edit.html.erb
<section class="span12 centred">
  <h1>Editing need</h1>

  <%= render 'form' %>
</section>

<% content_for :current_state, @need.status %>

app/views/needs/index.html.erb
<section id="needs" class="row-fluid">

  <%= render :partial => "needs_display", :locals => { :needs => @needs } %>

</div>

<% content_for :current_state, params[:in_state] %>

app/views/needs/new.html.erb
<section class="span12 centred">
  <h1>Enter a new need</h1>

  <p class="hints">Pithily capture a user need, e.g. pay my council tax, find out about childcare, find a job</p>

  <%= render 'form' %>
</section>

<% content_for :current_state, 'new' %>

app/views/needs/print.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Need-o-Tron</title>
  <style type="text/css">
      body {margin:0; font-family:helvetica;}
      .bleed {padding-right:8mm; border-right:1px dashed #000; width:108mm; height:60mm;}
      .label {border:solid 2mm #000;padding:0; position:relative; width:100mm; height:56mm; overflow:hidden;}
      .label h1 {font-size:5mm; margin:0; padding:3mm 0 0 3mm;}
      .label h2 {font-size:6mm; text-align:center; margin:0;border-bottom: solid 1mm #000;}
      .label h3 {font-size:6mm; text-align:center; margin:0;
          position:absolute; bottom:0;left:0; right:0; border-top: solid 1mm #000;}
      .label p {font-size:4mm; padding:3mm;margin:0;}
  </style>
</head>
<body onload="window.print();">
  <div class="bleed">
    <div class="label">
      <h2><%= @need.kind %> - #<%= @need.id %></h2>
      <h1><%= @need.title %></h1>
      <p><%= markdown @need.description %></p>
      <h3><%= @need.named_priority %></h3>
    </div>
  </div>
</body>
</html>

app/views/needs/show.html.erb
<% content_for(:title) { @need.title } %>
<section id="need" class="span12 centred">
  <header>
    <h2 class="need-status-block <%= @need.status %> span3">
      <p class="need-id">#<%= @need.id %></p>
      <p class="need-status"><%= status_name @need.status %></p>
    </h2>

    <h1><%= @need.title %></h1>
    <% if current_user.is_admin? %>
      <p class="need-actions"><%= link_to 'Edit', edit_need_path(@need) %></p>
    <% end %>
  </header>

  <% if @need.decision_made? %>
    <p class="need-decision">
      <%= @need.reason_for_decision %> &mdash; decided by <%= @need.decision_maker.name %> on <%= @need.decision_made_at.strftime("%d %b %Y") %>
    </p>
  <% end %>
  <% if @need.status == Need::DONE and @need.url.present? %>
    <p class="need-decision done">
      This need is live &mdash; <%= link_to @need.url, @need.url %>
    </p>
  <% end %>

  <% if @need.description.present? %>
    <div class="need-description">
      <%= markdown @need.description %>
    </div>
  <% end %>

  <% unless @need.status == Need::ICEBOX %>
    <div class="need-section sources">
      <h2>Why are we doing this need?</h2>

      <ul>
        <% @need.sources.each do |source| %>
        <li>
          <h3>[<%= source.kind.humanize %>] &mdash; <%= source.title %> <%= link_to "edit", edit_need_source_path(@need, source) %></h3>
          <p>
            <% if source.url.present? %><%= link_to source.url, source.url %><br><% end %>
            <% if source.body.present? %><%= source.body %><% end %>
          </p>
        </li>
        <% end %>
      </ul>

      <p><%= link_to "Add a new source", new_need_source_path(@need), :class => 'button' %></p>
    </div>
  <% end %>

  <% if @need.formatting_decision_made? %>
  <div class="need-section">
    <% if @need.kind.present? %>
      <h2>Why is this a <%= @need.kind %>?</h2>
    <% else %>
      <h2>What reasons for the formatting decision?</h2>
    <% end %>

    <p><%= @need.reason_for_formatting_decision %></p>
    <p>Decided by <%= @need.formatting_decision_maker.name %> on <%= @need.formatting_decision_made_at.strftime("%d %b %Y") %>.</p>
  </div>
  <% end %>

  <div id="need-meta" class="row">
    <div class="span8">
      <table class="table table-striped">
        <tr>
          <th scope="row">Format type</th>
          <td><%= @need.kind %></td>
        </tr>
        <tr>
          <th scope="row">Created</th>
          <td><%= time_ago_in_words(@need.created_at) %> ago</td>
        </tr>
        <tr>
          <th scope="row">Updated</th>
          <td><%= time_ago_in_words(@need.updated_at) %> ago</td>
        </tr>
        <tr>
          <th scope="row">Added By</th>
          <td><% if @need.creator.present? %><%= @need.creator.name %><% else %>None<% end %></td>
        </tr>
        <tr>
          <th scope="row">Tags</th>
          <td><%= @need.tag_list %></td>
        </tr>
        <tr>
          <th scope="row">Priority</th>
          <td><%= @need.named_priority %></td>
        </tr>
        <tr>
          <th scope="row">Policy Owner</th>
          <td><%= @need.current_accountability_names.join(', ') rescue '' %></td>
        </tr>
        <tr>
          <th scope="row">Fact Checkers</th>
          <td><%= @need.current_fact_checker_emails.join(', ') %></td>
        </tr>
        <% if @need.writing_department %>
        <tr>
          <th scope="row">Writing Team</th>
          <td><%= @need.writing_department.name %></td>
        </tr>
        <% end %>
      </table>
    </div>

    <% if current_user.is_admin? %>
    <div class="span4 need-toolbox">
      <% if @need.status == Need::NEW %>
        <%= button_to 'Submit for review', need_path(@need, :need => {:status => Need::READY_FOR_REVIEW}), :method => :put, :class => 'btn btn-block btn-primary btn-large' %>
        <p style="font-size: 0.85em">Submit a need for review once evidence for the need has been provided.</p>
      <% end %>

      <% if @need.format_assigned? %>
        <%= start_work_link @need %>
        <%= assign_work_link @need %>
        <p><%= link_to 'Print label', print_need_path(@need), :class => 'btn btn-block btn-large', :target => '_new' %></p>
      <% end %>

      <% if ! @need.in_progress? %>
        <p><%= button_to "Destroy need", @need, :method => :delete, :confirm => "Are you sure you want to permanently destroy this need?", :class => "btn btn-large btn-block btn-danger" %></p>
        <p style="font-size: 0.85em">(Please destroy sparingly &mdash; it's for cleaning up data rather than rejecting needs.)</p>
      <% end %>
    </div>
    <% end %>

  </div>

  <div id="need-progress">
    <% if @need.errors.any? %>
      <%= render 'errors' %>
    <% end %>

    <% if current_user.is_admin? %>
      <% if @need.status == Need::READY_FOR_REVIEW %>
        <%= render 'decision' %>
      <% elsif @need.being_worked_on? and @need.status != Need::DONE %>
        <%= render 'mark_done' %>
      <% end %>

      <% unless [ Need::ICEBOX, Need::DONE ].include?(@need.status) %>
        <%= render 'icebox' %>
      <% end %>
    <% else %>
      <div class="icebox">
        <h3>This need is being reviewed by our team</h3>
      </div>
    <% end %>
  </div><!-- end need-progress -->

  <br class="clear">
</section>

<% content_for :current_state, @need.status %>