config/routes.rb
NeedOTron::Application.routes.draw do
  resources :needs do
    collection do
      resource :imports, :only => [:new, :create]
    end
    resources :sources
    resources :fact_checkers do
      collection do
        get :search
      end
    end
    resources :accountabilities do
      collection do
        get :search
      end
    end
    member do
      get 'print'
    end
  end

  match 'search(/*filters)' => 'search#index', as: 'filtered_search'
  match 'search' => 'search#index', as: 'search'
  root :to => "search#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) + " - " if content_for?(:title) %>Need-o-tron</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-static-top">
      <div class="navbar-inner">
        <%= link_to "GOV.UK Need-o-tron", root_path, :class => 'brand' %>
        <nav role="navigation" class="nav-collapse">
          <ul class="nav">
            <li><%= link_to 'All needs', search_path %></li>
            <li><a class="new" href="<%= search_link_for_page({}, {status: 'new'}, 1) %>">New needs (<%= Need.in_state('new').count %>)</a></li>
            <% if current_user.is_admin? %>
              <li><%= link_to 'Enter a new need', new_need_path %></li>
            <% end %>
          </ul>
          <ul class="nav pull-right">
            <li><%= link_to 'Sign out', gds_sign_out_path %></li>
          </ul>
          <p class="navbar-text pull-right">Hello, <a href="<%= Plek.current.find('signon') %>"><%= current_user.name %></a></p>
        </nav>
      </div>
    </header>

    <div id="main" class="container-fluid <%= yield :current_state %>">
      <% flash.each do |k, v| %>
        <div class="alert" id="flash-<%= k %>"><%= v %></div>
      <% end %>

      <div class="row-fluid">
        <div class="pull-right">
          <div class="search">
            <%= form_tag search_path, :class => "form-search" do %>
              <label>Search for:
                <%= text_field_tag :query, params[:query], :class => "input-medium search-query" %>
              </label>
              <%= submit_tag "Search", :class => "btn" %>
            <% end %>
          </div>
        </div>
      </div>

      <%= yield %>

      <hr>

      <footer>
        <p>&copy; GDS. <span class="pull-right">Need-o-tron release: <%= CURRENT_RELEASE_SHA %></span></p>
      </footer>
    </div>

    <%= yield :extra_javascript %>
  </body>
</html>